language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  fast_finish: True
  # Allow py3.4 to fail; conda-forge no longer supports it
  allow_failures:
    - python: "3.4"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install dask numba numpy pandas pillow pytest toolz xarray datashape colorcet rasterio scikit-image param
  - conda install -c gbrener -c conda-forge xarray # remove this line when xarray >= 0.9.7

  # Optional dependencies, for testing only
  - conda install matplotlib
  # Dependencies for notebook & lint checking only
  - conda install jupyter flake8

  - python setup.py develop --no-deps

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then py.test datashader --doctest-modules --doctest-ignore-import-errors --verbose; else py.test datashader --verbose; fi
    - python examples/test_notebooks.py
    - flake8 --ignore E,W datashader examples
    - python examples/test_notebooks.py lint

notifications:
  email: false
